# Kafka topic name required by KafkaProducer
general.kafka-topic=test-topic

# Kafka bootstrap servers (Testcontainers will override during tests, but this avoids startup errors)
spring.kafka.bootstrap-servers=localhost:9092